volumes:
  redis:

networks:
  traefik:
    external: true
  internal:
    internal: true

services:
  nextcloud:
    image: "${IMAGE:-nextcloud}:${VERSION:-latest}"
    container_name: "${NAME:-nextcloud}"
    mem_limit: ${MEM_LIMIT:-2g}
    environment:
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT:-1024M}"
    labels:
      - "traefik.http.routers.${ROUTER:-nextcloud}.rule=Host(`${DOMAIN:-cloud.local.krislamo.org}`)"
      - "traefik.http.routers.${ROUTER:-nextcloud}.entrypoints=${ENTRYPOINT:-web}"
      - "traefik.http.routers.${ROUTER:-nextcloud}.tls=${ENABLE_TLS:-false}"
      - "traefik.http.routers.${ROUTER:-nextcloud}.middlewares=${MIDDLEWARES:-nextcloud-webdav}"
      - "traefik.http.services.${ROUTER:-nextcloud}.loadbalancer.server.port=${CONTAINER_PORT:-80}"
      - "traefik.http.middlewares.${ROUTER:-nextcloud}-webdav.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.${ROUTER:-nextcloud}-webdav.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.middlewares.${ROUTER:-nextcloud}-webdav.redirectregex.permanent=true"
      - "traefik.docker.network=${NETWORK:-traefik}"
      - "traefik.enable=${ENABLE:-true}"
    networks:
      - internal
      - "${NETWORK:-traefik}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "${DATA:?}:/var/www/html"
  redis:
    image: "redis:${REDIS_VERSION:-latest}"
    container_name: "${NAME:-nextcloud}-redis"
    command: redis-server --requirepass ${REDIS_PASSWORD:?}
    networks:
      - internal
    volumes:
      - redis:/data
